# Generated by Django 5.2.11 on 2026-03-01 23:06

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_url', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_to', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('backgroundImage', models.CharField(blank=True, max_length=5000000, null=True)),
                ('videoUrl', models.TextField(blank=True, null=True)),
                ('bg_type', models.CharField(default='image', max_length=50)),
                ('bg_gradient', models.JSONField(default=dict)),
                ('alignment', models.CharField(default='center', max_length=50)),
                ('content_x', models.IntegerField(default=50)),
                ('content_y', models.IntegerField(default=50)),
                ('title_font', models.CharField(default='Outfit', max_length=100)),
                ('title_color', models.CharField(default='#ffffff', max_length=50)),
                ('title_size', models.CharField(default='text-5xl', max_length=50)),
                ('subtitle_font', models.CharField(default='Outfit', max_length=100)),
                ('subtitle_size', models.CharField(default='text-xl', max_length=50)),
                ('subtitle_color', models.CharField(default='#ffffff', max_length=50)),
                ('description_color', models.CharField(default='#ffffff', max_length=50)),
                ('ctaText', models.CharField(blank=True, max_length=100, null=True)),
                ('ctaLink', models.CharField(blank=True, max_length=255, null=True)),
                ('secondaryCtaText', models.CharField(blank=True, max_length=100, null=True)),
                ('secondaryCtaLink', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'heroes',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'navigation',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('shipping_address', models.JSONField(default=dict)),
                ('payment_details', models.JSONField(blank=True, default=dict, null=True)),
                ('device_location', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('layout', models.CharField(default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField()),
                ('images', models.JSONField(default=list)),
                ('category_ids', models.JSONField(default=list)),
                ('attributes', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ctaText', models.CharField(default='Learn More', max_length=100)),
                ('ctaLink', models.CharField(default='/products', max_length=255)),
                ('title_font', models.CharField(default='Outfit', max_length=100)),
                ('title_size', models.CharField(default='text-6xl', max_length=100)),
                ('title_color', models.CharField(default='#ffffff', max_length=20)),
                ('subtitle_font', models.CharField(default='Outfit', max_length=100)),
                ('subtitle_size', models.CharField(default='text-xs', max_length=100)),
                ('subtitle_color', models.CharField(default='#4ade80', max_length=20)),
                ('target_type', models.CharField(default='all', max_length=20)),
                ('target_ids', models.JSONField(blank=True, default=list)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('background_type', models.CharField(default='color', max_length=20)),
                ('background_image', models.CharField(blank=True, max_length=255, null=True)),
                ('background_video', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('background_gradient', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('current_quantity', models.IntegerField()),
                ('low_stock_threshold', models.IntegerField()),
                ('movements', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnailImage', models.CharField(blank=True, max_length=255, null=True)),
                ('heroImage', models.CharField(blank=True, max_length=255, null=True)),
                ('shortExcerpt', models.TextField(blank=True, null=True)),
                ('fullStoryContent', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('other_description', models.TextField(blank=True, null=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='open', max_length=20)),
                ('conversations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('colors', models.JSONField(default=dict)),
                ('dark_mode_colors', models.JSONField(blank=True, default=dict, null=True)),
                ('light_mode_colors', models.JSONField(blank=True, default=dict, null=True)),
                ('button_styles', models.JSONField(blank=True, default=dict, null=True)),
                ('typography', models.JSONField(default=dict)),
                ('animation_defaults', models.JSONField(blank=True, default=dict, null=True)),
                ('global_background', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
    ]
