# Generated by Django 5.2.11 on 2026-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='bg_blur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='bg_brightness',
            field=models.IntegerField(default=100),
        ),
    ]
