# Generated by Django 5.2.11 on 2026-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hero_bg_blur_hero_bg_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bg_blur',
            field=models.IntegerField(default=0, help_text='Background blur amount (0-100px)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_brightness',
            field=models.IntegerField(default=100, help_text='Background brightness percentage'),
        ),
    ]
