# Generated by Django 5.2.11 on 2026-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_theme_bg_blur_theme_bg_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='animation_type',
            field=models.CharField(default='fade-up', max_length=50),
        ),
        migrations.AddField(
            model_name='hero',
            name='parallax_speed',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_urls',
            field=models.JSONField(blank=True, default=dict, help_text='Links to Google Fonts or custom font files'),
        ),
        migrations.AddField(
            model_name='theme',
            name='footer_contact',
            field=models.JSONField(blank=True, default=dict, help_text='Phone, Email, Address, Social links for footer'),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='ticker_style',
            field=models.JSONField(blank=True, default=dict, help_text='Styles for the marquee (bg_color, text_color, etc.)'),
        ),
        migrations.AddField(
            model_name='theme',
            name='ticker_text',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for the top marquee'),
        ),
    ]
