# Generated by Django 5.2.11 on 2026-03-13 16:05

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hero_animation_type_hero_parallax_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBranding',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Videeptha Foods', max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ticker_text', models.JSONField(blank=True, default=list)),
                ('ticker_style', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_branding',
            },
        ),
        migrations.CreateModel(
            name='WebsiteFooter',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Footer', max_length=100)),
                ('footer_contact', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_footer',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTheme',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('colors', models.JSONField(default=dict)),
                ('dark_mode_colors', models.JSONField(blank=True, default=dict, null=True)),
                ('light_mode_colors', models.JSONField(blank=True, default=dict, null=True)),
                ('button_styles', models.JSONField(blank=True, default=dict, null=True)),
                ('global_background', models.JSONField(blank=True, default=dict, null=True)),
                ('bg_blur', models.IntegerField(default=0)),
                ('bg_brightness', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_theme',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTypography',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Typography', max_length=100)),
                ('font_urls', models.JSONField(blank=True, default=dict)),
                ('typography_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_typography',
            },
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AlterModelTable(
            name='category',
            table='website_categories',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='website_coupons',
        ),
        migrations.AlterModelTable(
            name='hero',
            table='website_heroes',
        ),
        migrations.AlterModelTable(
            name='navigation',
            table='website_navigation',
        ),
        migrations.AlterModelTable(
            name='order',
            table='website_orders',
        ),
        migrations.AlterModelTable(
            name='page',
            table='website_pages',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='website_policies',
        ),
        migrations.AlterModelTable(
            name='product',
            table='website_products',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='website_promotions',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='website_stock',
        ),
        migrations.AlterModelTable(
            name='story',
            table='website_stories',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='website_support_tickets',
        ),
    ]
