# Generated by Django 5.2.11 on 2026-02-24 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedprofile',
            name='country_code',
            field=models.CharField(db_index=True, default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='encryptedprofile',
            name='preferred_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address'), ('both', 'Both')], default='shipping', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('_full_name', models.TextField(db_column='full_name')),
                ('_phone', models.TextField(db_column='phone')),
                ('_street_address', models.TextField(db_column='street_address')),
                ('_city', models.TextField(db_column='city')),
                ('_state', models.TextField(db_column='state')),
                ('_pincode', models.TextField(db_column='pincode')),
                ('_country', models.TextField(db_column='country', default='India')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
