# Generated by Django 5.2.11 on 2026-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encryptedprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedprofile',
            name='_cart_data',
            field=models.TextField(blank=True, db_column='cart_data', null=True),
        ),
    ]
