# Generated by Django 5.2.11 on 2026-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_encryptedprofile__cart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedprofile',
            name='_cart_data',
        ),
        migrations.AddField(
            model_name='encryptedprofile',
            name='cart_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
