# Generated by Django 5.2.11 on 2026-02-25 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_encryptedprofile__cart_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='_city',
            new_name='enc_city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_country',
            new_name='enc_country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_full_name',
            new_name='enc_full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_phone',
            new_name='enc_phone',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_pincode',
            new_name='enc_pincode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_state',
            new_name='enc_state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_street_address',
            new_name='enc_street_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_signin_at', models.DateTimeField(blank=True, null=True)),
                ('_google_id', models.TextField(blank=True, db_column='google_id', null=True)),
                ('_full_name', models.TextField(blank=True, db_column='full_name', null=True)),
                ('_avatar_url', models.TextField(blank=True, db_column='avatar_url', null=True)),
                ('_raw_data', models.TextField(blank=True, db_column='raw_data', null=True)),
                ('_phone', models.TextField(blank=True, db_column='phone', null=True)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('plain_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('country_code', models.CharField(db_index=True, default='IN', max_length=10)),
                ('preferred_currency', models.CharField(default='INR', max_length=10)),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('assistant_admin', 'Assistant Admin'), ('product_manager', 'Product Manager')], default='assistant_admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_admin_profile',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_signin_at', models.DateTimeField(blank=True, null=True)),
                ('_google_id', models.TextField(blank=True, db_column='google_id', null=True)),
                ('_full_name', models.TextField(blank=True, db_column='full_name', null=True)),
                ('_avatar_url', models.TextField(blank=True, db_column='avatar_url', null=True)),
                ('_raw_data', models.TextField(blank=True, db_column='raw_data', null=True)),
                ('_phone', models.TextField(blank=True, db_column='phone', null=True)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('plain_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('country_code', models.CharField(db_index=True, default='IN', max_length=10)),
                ('preferred_currency', models.CharField(default='INR', max_length=10)),
                ('cart_data', models.JSONField(blank=True, default=list)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_customer_profile',
            },
        ),
        migrations.DeleteModel(
            name='EncryptedProfile',
        ),
    ]
