# Generated by Django 5.2.11 on 2026-02-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename__city_address_enc_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='preferred_currency',
        ),
    ]
