# Generated by Django 5.2.11 on 2026-03-13 15:44

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_id_alter_adminprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('current_watching', models.IntegerField(default=0)),
                ('cart_adds', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_product_analytics',
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favorites_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='enc_country',
            field=models.TextField(db_column='country', default='USA'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='country_code',
            field=models.CharField(db_index=True, default='US', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_favorite',
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
